version: "1.0"
info:
  model: int-scaffold
packages:
- name: Vikpa_wmIoIntegrationsProject
  gitServerName: wm.ioTest
  gitUrl: https://github.com/vikpa309/Vikpa_wmIoIntegrationsProject
  gitUsername: vikpa309
  gitBranch: main
services:
- serviceName: project.vikpa_wmiointegrations.integrations:testing
  packages:
  - name: Vikpa_wmIoIntegrationsProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: project.vikpa_wmiointegrations.integrations:getCallOnPrem
  packages:
  - name: Vikpa_wmIoIntegrationsProject
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: project.vikpa_wmiointegrations.integrations:globalVariable
  packages:
  - name: Vikpa_wmIoIntegrationsProject
    version: "1.0"
